'use strict';
(()=>{
const $=s=>document.querySelector(s);let canvas,ctx,w=0,h=0,dpr=1,nodes=[],edges=[],hover=null,drag=false,path=[],live=false,projectionMode=false,baseUrl='https://agentropolis-agent-mcp.chaoswired.workers.dev',revision=null,pollTimer=null;
const palette={evidence:'#00f5d4',human_editable:'#00bde8',retrieval:'#a75cff',ontology:'#f3cf72',cognition:'#ff5da2',governance:'#ff2a4f',note:'#00bde8',claim:'#f3cf72',entity:'#a75cff',decision:'#ff5da2',challenge:'#ff2a4f',canon:'#00f5d4',artifact:'#7ee7ff',memory:'#d7e3f2'};
function resize(){if(!canvas)return;const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);w=Math.max(320,r.width);h=Math.max(300,r.height);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
function seed(s){let x=2166136261;for(const c of String(s))x=Math.imul(x^c.charCodeAt(0),16777619);return()=>((x=Math.imul(x^x>>>15,2246822519))>>>0)/4294967295}
function preview(){return {layers:{evidence:['WikiVault evidence records','canon records','provenance','conflicts','review queue'],human_editable:['Obsidian vault','local node wiki','idea/capability files'],retrieval:['llm-wiki index','RAG chunks','archive/review/security retrieval scopes'],ontology:['gbrain entities','relationships','claims','confidence','evidence links'],cognition:['Mind Vault','lens router','attention market','cognitive assembly','collision engine','Heretic slot','Meta-J'],governance:['ASBE/AEGIS policy gate','authority profile','human approval','execution receipts']},authority:'READ_ONLY',placement:'Layer 1'} }
function buildArchitecture(model){projectionMode=false;nodes=[];edges=[];const groups=Object.entries(model.layers||{});const cx=w*.5,cy=h*.48,rx=Math.min(w*.35,290),ry=Math.min(h*.36,210);groups.forEach(([g,items],gi)=>{const a0=-Math.PI*.92+gi*(Math.PI*1.84/Math.max(groups.length-1,1));items.forEach((label,i)=>{const rnd=seed(g+label),a=a0+(rnd()-.5)*.55,r=.35+.55*rnd(),hem=i%2?1:-1;nodes.push({id:g+':'+label,label,title:label,group:g,type:g,x:cx+Math.cos(a)*rx*r+hem*18,y:cy+Math.sin(a)*ry*r+(rnd()-.5)*28,r:5+rnd()*5,color:palette[g]||'#dff',evidenceState:'ARCHITECTURE',challengeState:'none',confidence:null,torque:null})})});for(let i=0;i<nodes.length;i++){const same=nodes.filter(n=>n.group===nodes[i].group);const j=same[(same.indexOf(nodes[i])+1)%same.length];if(j&&j!==nodes[i])edges.push({a:nodes[i],b:j,relation:'architecture'});if(i%3===0&&nodes[i+1])edges.push({a:nodes[i],b:nodes[i+1],relation:'architecture'})}updateStats(model)}
function buildProjection(model){projectionMode=true;nodes=[];edges=[];const cx=w*.5,cy=h*.48,rx=Math.min(w*.38,310),ry=Math.min(h*.38,230);const sourceNodes=Array.isArray(model.nodes)?model.nodes:[];sourceNodes.forEach((raw,i)=>{const rnd=seed(raw.id),a=rnd()*Math.PI*2,r=Math.sqrt(rnd())*.86+.08,hem=rnd()>.5?1:-1,torque=Number.isFinite(raw.torque)?raw.torque:.35,challenged=raw.challengeState&&raw.challengeState!=='none';nodes.push({...raw,label:raw.title||raw.id,group:raw.type||'memory',x:cx+hem*22+Math.cos(a)*rx*r,y:cy+Math.sin(a)*ry*r,r:4+torque*7,color:challenged?palette.challenge:(palette[raw.type]||palette.memory)})});const byId=new Map(nodes.map(n=>[n.id,n]));for(const raw of Array.isArray(model.edges)?model.edges:[]){const a=byId.get(raw.from),b=byId.get(raw.to);if(a&&b)edges.push({a,b,relation:raw.relation||'related_to',weight:raw.weight??.5,confidence:raw.confidence})}updateStats({authority:model.authority||'DERIVED_READ_ONLY_PROJECTION',placement:`projection · ${model.source||'WikiVault'}`})}
function updateStats(model){$('#neuralNodeCount').textContent=nodes.length;$('#neuralEdgeCount').textContent=edges.length;$('#neuralAuthority').textContent=model.authority||'READ_ONLY';$('#neuralPlacement').textContent=model.placement||'Layer 1';const s=$('#neuralStatus');const rev=revision?` · ${revision.slice(0,10)}`:'';s.textContent=projectionMode&&live?`LIVE MEMORY PROJECTION${rev}`:live?`LIVE · RECEIPT-BACKED JSPACE${rev}`:'CANONICAL PREVIEW · LIVE PROJECTION UNAVAILABLE';s.className='readout '+(live?'neural-status-live':'neural-status-preview')}
async function sync(){baseUrl=($('#baseUrl')?.value||baseUrl).replace(/\/+$/,'');let architecture=preview();live=false;try{const headers={accept:'application/json'};if(revision)headers['if-none-match']=`"${revision}"`;const p=await fetch(`${baseUrl}/api/jspace?view=projection`,{headers});if(p.status===304){live=true;return}if(p.ok){const d=await p.json();if(d?.projection?.nodes){revision=d.revision||null;live=Boolean(d.receipt?.id);buildProjection(d.projection);return}}}catch{}
try{const r=await fetch(`${baseUrl}/api/jspace?view=manifest`,{headers:{accept:'application/json'}});if(!r.ok)throw Error(String(r.status));const d=await r.json();if(d?.jspace?.layers){architecture=d.jspace;live=Boolean(d.receipt?.id);revision=null}}catch{}buildArchitecture(architecture)}
function edgeColor(e){if(/contradict|challenge|conflict/.test(e.relation))return'rgba(255,42,79,.48)';if(/support|evidence/.test(e.relation))return'rgba(0,245,212,.34)';return'rgba(100,220,230,.15)'}
function brain(t){ctx.clearRect(0,0,w,h);const cx=w*.5,cy=h*.48,rx=Math.min(w*.31,250),ry=Math.min(h*.33,195);ctx.save();ctx.strokeStyle='rgba(0,245,212,.15)';ctx.lineWidth=1.2;ctx.shadowColor='#00f5d4';ctx.shadowBlur=12;for(const side of [-1,1]){ctx.beginPath();for(let i=0;i<=80;i++){const a=Math.PI*2*i/80,x=cx+side*20+Math.cos(a)*rx*.48,y=cy+Math.sin(a)*ry*(.82+.06*Math.sin(a*5+side));i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}ctx.restore();edges.forEach(e=>{ctx.strokeStyle=edgeColor(e);ctx.lineWidth=1+(e.weight||.25)*1.4;ctx.beginPath();ctx.moveTo(e.a.x,e.a.y);ctx.lineTo(e.b.x,e.b.y);ctx.stroke()});nodes.forEach((n,i)=>{const pulse=1+.18*Math.sin(t*.002+i)+(n.torque||0)*.12,challenged=n.challengeState&&n.challengeState!=='none',verified=n.evidenceState==='VERIFIED'||n.verificationState==='verified';ctx.beginPath();ctx.fillStyle=n.color;ctx.shadowColor=challenged?'#ff2a4f':n.color;ctx.shadowBlur=hover===n?22:8+(n.torque||0)*10;ctx.globalAlpha=hover===n?1:.58+(n.confidence??.45)*.35;ctx.arc(n.x,n.y,n.r*pulse,0,Math.PI*2);ctx.fill();if(verified||challenged){ctx.strokeStyle=challenged?'#ff2a4f':'#ffffff';ctx.lineWidth=challenged?2:1;ctx.stroke()}ctx.globalAlpha=1;ctx.shadowBlur=0});if(path.length>1){ctx.strokeStyle='#ffffff';ctx.lineWidth=2;ctx.shadowColor='#00f5d4';ctx.shadowBlur=14;ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.shadowBlur=0}requestAnimationFrame(brain)}
function hit(x,y){return nodes.find(n=>Math.hypot(x-n.x,y-n.y)<=n.r+7)||null}
function pointer(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showTip(n,p){const tip=$('#neuralTooltip');if(!n){tip.classList.remove('visible');return}const state=n.evidenceState||'UNVERIFIED',challenge=n.challengeState&&n.challengeState!=='none'?` · CHALLENGED:${n.challengeState}`:'',torque=Number.isFinite(n.torque)?` · TORQUE ${Math.round(n.torque*100)}%`:'';tip.innerHTML=`<b>${esc(n.title||n.label)}</b><small>${esc((n.type||n.group||'memory').replaceAll('_',' ').toUpperCase())} · ${esc(state)}${esc(challenge)}${esc(torque)}</small>${n.namespace?`<small>${esc(n.namespace)}</small>`:''}${n.sourceRef?`<small>REF · ${esc(n.sourceRef)}</small>`:''}${n.provenanceHash?`<small>PROV · ${esc(n.provenanceHash.slice(0,18))}</small>`:''}`;tip.style.left=Math.min(w-260,p.x)+'px';tip.style.top=Math.max(8,p.y)+'px';tip.classList.add('visible')}
function init(){canvas=$('#neuralCanvas');if(!canvas)return;ctx=canvas.getContext('2d');resize();addEventListener('resize',()=>{resize();sync()});canvas.addEventListener('pointermove',e=>{const p=pointer(e);hover=hit(p.x,p.y);showTip(hover,p);if(drag){path.push(p);if(path.length>160)path.shift()}});canvas.addEventListener('pointerdown',e=>{drag=true;path=[pointer(e)];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',e=>{drag=false;canvas.releasePointerCapture(e.pointerId)});canvas.addEventListener('pointerleave',()=>{hover=null;showTip(null,{})});$('#neuralSync')?.addEventListener('click',sync);$('#neuralClear')?.addEventListener('click',()=>path=[]);sync();pollTimer=setInterval(()=>{if(!document.hidden)sync()},30000);addEventListener('beforeunload',()=>clearInterval(pollTimer));requestAnimationFrame(brain)}
addEventListener('DOMContentLoaded',init);
})();