'use strict';
(()=>{
const $=s=>document.querySelector(s);let canvas,ctx,w=0,h=0,dpr=1,nodes=[],edges=[],hover=null,drag=false,path=[],live=false,lastSync=0,baseUrl='https://agentropolis-agent-mcp.chaoswired.workers.dev';
const palette={evidence:'#00f5d4',human_editable:'#00bde8',retrieval:'#a75cff',ontology:'#f3cf72',cognition:'#ff5da2',governance:'#ff2a4f'};
function resize(){if(!canvas)return;const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);w=Math.max(320,r.width);h=Math.max(300,r.height);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
function seed(s){let x=2166136261;for(const c of s)x=Math.imul(x^c.charCodeAt(0),16777619);return()=>((x=Math.imul(x^x>>>15,2246822519))>>>0)/4294967295}
function preview(){return {layers:{evidence:['WikiVault evidence records','canon records','provenance','conflicts','review queue'],human_editable:['Obsidian vault','local node wiki','idea/capability files'],retrieval:['llm-wiki index','RAG chunks','archive/review/security retrieval scopes'],ontology:['gbrain entities','relationships','claims','confidence','evidence links'],cognition:['Mind Vault','lens router','attention market','cognitive assembly','collision engine','Heretic slot','Meta-J'],governance:['ASBE/AEGIS policy gate','authority profile','human approval','execution receipts']},authority:'READ_ONLY',placement:'Agentropolis Layer 1 / Intelligence Grid infrastructure'} }
function build(model){nodes=[];edges=[];const groups=Object.entries(model.layers||{});const cx=w*.5,cy=h*.48,rx=Math.min(w*.35,290),ry=Math.min(h*.36,210);groups.forEach(([g,items],gi)=>{const a0=-Math.PI*.92+gi*(Math.PI*1.84/Math.max(groups.length-1,1));items.forEach((label,i)=>{const rnd=seed(g+label),a=a0+(rnd()-.5)*.55,r=.35+.55*rnd(),hem=i%2?1:-1;nodes.push({id:g+':'+label,label,group:g,x:cx+Math.cos(a)*rx*r+hem*18,y:cy+Math.sin(a)*ry*r+(rnd()-.5)*28,r:5+rnd()*5,color:palette[g]||'#dff'})})});for(let i=0;i<nodes.length;i++){const same=nodes.filter(n=>n.group===nodes[i].group);const j=same[(same.indexOf(nodes[i])+1)%same.length];if(j&&j!==nodes[i])edges.push([nodes[i],j]);if(i%3===0&&nodes[i+1])edges.push([nodes[i],nodes[i+1]])}updateStats(model)}
function updateStats(model){$('#neuralNodeCount').textContent=nodes.length;$('#neuralEdgeCount').textContent=edges.length;$('#neuralAuthority').textContent=model.authority||'READ_ONLY';$('#neuralPlacement').textContent=model.placement||'Layer 1';const s=$('#neuralStatus');s.textContent=live?'LIVE · RECEIPT-BACKED JSPACE':'CANONICAL PREVIEW · WORKER UNAVAILABLE';s.className='readout '+(live?'neural-status-live':'neural-status-preview')}
async function sync(){baseUrl=($('#baseUrl')?.value||baseUrl).replace(/\/+$/,'');let model=preview();live=false;try{const r=await fetch(`${baseUrl}/api/jspace?view=manifest`,{headers:{accept:'application/json'}});if(!r.ok)throw Error(String(r.status));const d=await r.json();if(d?.jspace?.layers){model=d.jspace;live=Boolean(d.receipt?.id);lastSync=Date.now()}}catch{}build(model)}
function brain(t){ctx.clearRect(0,0,w,h);const cx=w*.5,cy=h*.48,rx=Math.min(w*.31,250),ry=Math.min(h*.33,195);ctx.save();ctx.strokeStyle='rgba(0,245,212,.18)';ctx.lineWidth=1.2;ctx.shadowColor='#00f5d4';ctx.shadowBlur=12;for(const side of [-1,1]){ctx.beginPath();for(let i=0;i<=80;i++){const a=Math.PI*2*i/80,x=cx+side*20+Math.cos(a)*rx*.48,y=cy+Math.sin(a)*ry*(.82+.06*Math.sin(a*5+side));i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}ctx.restore();edges.forEach(([a,b],i)=>{ctx.strokeStyle=i%5===0?'rgba(255,42,79,.18)':'rgba(100,220,230,.12)';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()});nodes.forEach((n,i)=>{const pulse=1+.22*Math.sin(t*.002+i);ctx.beginPath();ctx.fillStyle=n.color;ctx.shadowColor=n.color;ctx.shadowBlur=hover===n?20:9;ctx.globalAlpha=hover===n?1:.72;ctx.arc(n.x,n.y,n.r*pulse,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.shadowBlur=0});if(path.length>1){ctx.strokeStyle='#ffffff';ctx.lineWidth=2;ctx.shadowColor='#00f5d4';ctx.shadowBlur=14;ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.shadowBlur=0}requestAnimationFrame(brain)}
function hit(x,y){return nodes.find(n=>Math.hypot(x-n.x,y-n.y)<=n.r+7)||null}
function pointer(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function showTip(n,p){const tip=$('#neuralTooltip');if(!n){tip.classList.remove('visible');return}tip.innerHTML=`<b>${n.label}</b><small>${n.group.replace('_',' ').toUpperCase()} · READ ONLY</small>`;tip.style.left=p.x+'px';tip.style.top=p.y+'px';tip.classList.add('visible')}
function init(){canvas=$('#neuralCanvas');if(!canvas)return;ctx=canvas.getContext('2d');resize();addEventListener('resize',()=>{resize();build(window.__jspaceNeuralModel||preview())});canvas.addEventListener('pointermove',e=>{const p=pointer(e);hover=hit(p.x,p.y);showTip(hover,p);if(drag){path.push(p);if(path.length>120)path.shift()}});canvas.addEventListener('pointerdown',e=>{drag=true;path=[pointer(e)];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',e=>{drag=false;canvas.releasePointerCapture(e.pointerId)});canvas.addEventListener('pointerleave',()=>{hover=null;showTip(null,{})});$('#neuralSync')?.addEventListener('click',sync);$('#neuralClear')?.addEventListener('click',()=>path=[]);sync();requestAnimationFrame(brain)}
addEventListener('DOMContentLoaded',init);
})();