'use strict';
const DB='agentropolis-media',STORE='hero-assets',KEY='hero-video',MAX=200*1024*1024;
const DISTRICTS=[
 {id:'grid',name:'GRID CORE',role:'Runtime, memory, dispatch, and registry substrate.',x:-5.5,z:-1.5,w:3.2,d:3.1,h:8.2,color:'#00f5d4',status:'online'},
 {id:'hermes',name:'HERMES DOCK',role:'Operator docking terminal for remote MCP configuration.',x:0,z:4.2,w:5.1,d:3.8,h:1.8,color:'#00bde8',status:'ready'},
 {id:'registry',name:'CAPABILITY REGISTRY',role:'Contract catalog for tools, Skills, and authority ceilings.',x:5.7,z:-1.8,w:3.5,d:3.4,h:7.4,color:'#a75cff',status:'online'},
 {id:'relay',name:'MCP RELAY',role:'Streamable HTTP gateway into the governed capability membrane.',x:-4.4,z:-7.2,w:3,d:3,h:5.6,color:'#39ff43',status:'remote'},
 {id:'vault',name:'RECEIPT VAULT',role:'Evidence store for execution, authority, and audit receipts.',x:4.3,z:-7.4,w:4.1,d:3.7,h:4.8,color:'#f3cf72',status:'sealed'},
 {id:'risk',name:'RISK GATE',role:'Anti-Moloch slowdown and request risk classification.',x:0,z:-12,w:6.4,d:2.7,h:3.8,color:'#ff2a4f',status:'active'}
];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbGet(){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function dbPut(file){const db=await openDb();return new Promise((resolve,reject)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put({blob:file,meta:{name:file.name,type:file.type,size:file.size}},KEY);t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
async function dbDelete(){const db=await openDb();return new Promise((resolve,reject)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).delete(KEY);t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
function normalize(value){try{const u=new URL(String(value||'').trim().replace(/\/+$/,''));if(u.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(u.hostname))return'';return u.toString().replace(/\/$/,'')}catch{return''}}
const canvas=$('#cityCanvas'),ctx=canvas.getContext('2d',{alpha:true});let width=0,height=0,dpr=1,yaw=-.18,pitch=.62,zoom=1,drag=false,lastX=0,lastY=0,selected=DISTRICTS[0],hotspots=[],focus=false,videoUrl='';
function resize(){dpr=Math.min(devicePixelRatio||1,2);width=innerWidth;height=innerHeight;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);canvas.style.width=width+'px';canvas.style.height=height+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
function project(x,y,z){const cy=Math.cos(yaw),sy=Math.sin(yaw),rx=x*cy-z*sy,rz=x*sy+z*cy;const cp=Math.cos(pitch),sp=Math.sin(pitch),ry=y*cp-rz*sp,depth=y*sp+rz*cp+30;const f=(Math.min(width,height)*1.08*zoom)/Math.max(8,depth);return{x:width*.58+rx*f,y:height*.58-ry*f,s:f,depth}}
function polygon(points,fill,stroke,glow=0){ctx.beginPath();points.forEach((p,i)=>(i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.save();ctx.strokeStyle=stroke;ctx.lineWidth=1.2;if(glow){ctx.shadowColor=stroke;ctx.shadowBlur=glow}ctx.stroke();ctx.restore()}}
function rgba(hex,a){const n=parseInt(hex.slice(1),16);return`rgba(${n>>16},${n>>8&255},${n&255},${a})`}
function drawMotherboard(t){const corners=[project(-18,0,-19),project(18,0,-19),project(18,0,12),project(-18,0,12)];const g=ctx.createLinearGradient(0,height*.3,0,height);g.addColorStop(0,'rgba(9,12,15,.92)');g.addColorStop(1,'rgba(1,2,4,.98)');polygon(corners,g,'rgba(0,245,212,.13)');for(let i=-16;i<=16;i+=2){const a=project(i,.02,-18),b=project(i,.02,11);ctx.strokeStyle=i%4===0?'rgba(0,189,232,.18)':'rgba(84,112,118,.08)';ctx.lineWidth=i%4===0?1.1:.7;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(let z=-18;z<=10;z+=2){const a=project(-17,.02,z),b=project(17,.02,z);ctx.strokeStyle=z%4===0?'rgba(255,42,79,.13)':'rgba(84,112,118,.07)';ctx.lineWidth=z%4===0?1.1:.7;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}const traces=[[[-14,-14],[-9,-14],[-9,-6],[-5,-6]],[[13,7],[9,7],[9,1],[5,1]],[[-14,7],[-10,7],[-10,2],[-4,2]],[[13,-15],[8,-15],[8,-10],[4,-10]],[[-2,8],[-2,3],[0,3],[0,-11]]];traces.forEach((pts,i)=>{ctx.save();ctx.strokeStyle=i%2?rgba('#ff2a4f',.65):rgba('#00f5d4',.72);ctx.shadowColor=i%2?'#ff2a4f':'#00f5d4';ctx.shadowBlur=9+Math.sin(t*.002+i)*4;ctx.lineWidth=1.5;ctx.beginPath();pts.forEach(([x,z],j)=>{const p=project(x,.04,z);j?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});ctx.stroke();ctx.restore();pts.forEach(([x,z],j)=>{if(j===0||j===pts.length-1){const p=project(x,.06,z);ctx.beginPath();ctx.fillStyle=i%2?'#ff2a4f':'#00f5d4';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;ctx.arc(p.x,p.y,2.4+Math.sin(t*.004+i)*.8,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}})})}
function buildingFaces(d){const x0=d.x-d.w/2,x1=d.x+d.w/2,z0=d.z-d.d/2,z1=d.z+d.d/2,y0=0,y1=d.h;return{a:project(x0,y0,z0),b:project(x1,y0,z0),c:project(x1,y0,z1),d:project(x0,y0,z1),A:project(x0,y1,z0),B:project(x1,y1,z0),C:project(x1,y1,z1),D:project(x0,y1,z1)}}
function drawBuilding(d,t){const v=buildingFaces(d),sel=d===selected;const front=[v.d,v.c,v.C,v.D],side=[v.c,v.b,v.B,v.C],top=[v.D,v.C,v.B,v.A];polygon(side,'rgba(3,7,10,.92)',rgba(d.color,sel?.95:.5),sel?18:7);polygon(front,'rgba(7,12,15,.96)',rgba(d.color,sel?1:.62),sel?22:9);const tg=ctx.createLinearGradient(0,v.D.y,0,v.d.y);tg.addColorStop(0,rgba(d.color,sel?.34:.22));tg.addColorStop(1,'rgba(3,7,10,.96)');polygon(top,tg,rgba(d.color,.86),sel?18:10);ctx.save();ctx.strokeStyle=d.color;ctx.shadowColor=d.color;ctx.shadowBlur=sel?20:11;ctx.globalAlpha=.75+.2*Math.sin(t*.002+d.x);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(v.D.x,v.D.y);ctx.lineTo(v.d.x,v.d.y);ctx.stroke();ctx.restore();const center=project(d.x,d.h+.5,d.z);ctx.font='800 11px Inter,system-ui';ctx.textAlign='center';ctx.fillStyle=sel?'#ffffff':'rgba(235,250,250,.86)';ctx.shadowColor='#000';ctx.shadowBlur=8;ctx.fillText(d.name,center.x,center.y);ctx.font='700 8px ui-monospace,monospace';ctx.fillStyle=d.color;ctx.fillText(d.status.toUpperCase(),center.x,center.y+13);ctx.shadowBlur=0;const base=project(d.x,0,d.z);hotspots.push({d,x:base.x,y:base.y-Math.abs(base.y-center.y)/2,r:Math.max(28,d.w*base.s*.55)})}
function drawAtmosphere(t){const glow=ctx.createRadialGradient(width*.58,height*.48,20,width*.58,height*.48,Math.max(width,height)*.5);glow.addColorStop(0,'rgba(0,245,212,.055)');glow.addColorStop(.42,'rgba(0,189,232,.022)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,width,height);for(let i=0;i<34;i++){const x=(i*173.7+t*.005*(i%3+1))%width,y=(i*91.3)%height*.72;ctx.fillStyle=i%4===0?'rgba(255,42,79,.38)':'rgba(0,245,212,.32)';ctx.fillRect(x,y,1.2,1.2)}}
function frame(t){ctx.clearRect(0,0,width,height);hotspots=[];drawAtmosphere(t);drawMotherboard(t);[...DISTRICTS].sort((a,b)=>project(a.x,0,a.z).depth-project(b.x,0,b.z).depth).forEach(d=>drawBuilding(d,t));requestAnimationFrame(frame)}
function choose(d){selected=d;$('#selectedName').textContent=d.name;$('#selectedRole').textContent=d.role;$('#selectedStatus').textContent=d.status.toUpperCase();$$('.directory button').forEach(b=>b.classList.toggle('selected',b.dataset.id===d.id))}
function buildDirectory(){const root=$('#directory');DISTRICTS.forEach(d=>{const b=document.createElement('button');b.dataset.id=d.id;b.innerHTML=`<i style="background:${d.color};color:${d.color}"></i><span>${d.name}</span><small>${d.status}</small>`;b.addEventListener('click',()=>choose(d));root.appendChild(b)});choose(selected)}
function setPanel(name){$$('.drawer').forEach(p=>{const open=p.id===`${name}Panel`;p.classList.toggle('open',open);p.setAttribute('aria-hidden',String(!open))});$$('.dock button').forEach(b=>b.classList.toggle('active',b.dataset.open===name))}
function closePanels(){$$('.drawer').forEach(p=>{p.classList.remove('open');p.setAttribute('aria-hidden','true')});$$('.dock button').forEach(b=>b.classList.remove('active'))}
function renderConfig(){const base=normalize($('#baseUrl').value)||'https://agentropolis-agent-mcp.chaoswired.workers.dev',url=`${base}/mcp`,mode=$('.segmented button.active').dataset.mode;$('#configOutput').textContent=JSON.stringify({mcpServers:{'agentropolis-grid':mode==='native'?{url,transport:'streamable-http'}:{command:'npx',args:['-y','mcp-remote',url]}}},null,2)}
async function checkRuntime(){const base=normalize($('#baseUrl').value),out=$('#healthReadout'),dot=$('#runtimeDot'),label=$('#runtimeLabel');if(!base){out.className='readout offline';out.textContent='Enter a valid HTTPS Worker URL.';return}out.className='readout checking';out.textContent='Checking /health and /.well-known/mcp.json ...';dot.className='led checking';label.textContent='CHECKING';try{const[h,m]=await Promise.all([fetch(`${base}/health`,{headers:{accept:'application/json'}}),fetch(`${base}/.well-known/mcp.json`,{headers:{accept:'application/json'}})]);if(!h.ok||!m.ok)throw Error(`health=${h.status}, manifest=${m.status}`);const health=await h.json(),manifest=await m.json();out.className='readout online';out.textContent=`ONLINE · ${health.service||'agentropolis-agent-mcp'} · tools=${manifest?.tools?.length??manifest?.capabilities?.tools?.length??'unknown'}`;dot.className='led online';label.textContent='ONLINE'}catch(e){out.className='readout offline';out.textContent=`UNREACHABLE · ${e.message}`;dot.className='led offline';label.textContent='OFFLINE'}}
function applyVideo(blob,meta){if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl=URL.createObjectURL(blob);const v=$('#heroVideo');v.src=videoUrl;v.play().catch(()=>{});$('#mediaReadout').textContent=`LOCAL HERO ACTIVE · ${meta.name}`;$('#mediaMeta').hidden=false;$('#mediaMeta').textContent=`${meta.name} · ${Math.round(meta.size/1024/1024)} MB · stored in this browser`;$('#clearHero').disabled=false}
async function uploadHero(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;const out=$('#mediaReadout');if(!['video/mp4','video/webm','video/ogg'].includes(file.type)){out.textContent='BLOCKED · Use MP4, WebM, or Ogg.';return}if(file.size>MAX){out.textContent='BLOCKED · Video exceeds 200 MB.';return}await dbPut(file);applyVideo(file,{name:file.name,size:file.size,type:file.type})}
async function clearHero(){await dbDelete();if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl='';const v=$('#heroVideo');v.pause();v.removeAttribute('src');v.load();$('#mediaReadout').textContent='Hero video cleared.';$('#mediaMeta').hidden=true;$('#clearHero').disabled=true}
canvas.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;yaw+=dx*.004;pitch=Math.max(.36,Math.min(.92,pitch+dy*.003))});canvas.addEventListener('pointerup',e=>{drag=false;canvas.releasePointerCapture(e.pointerId);const hit=hotspots.filter(h=>Math.hypot(e.clientX-h.x,e.clientY-h.y)<h.r).sort((a,b)=>a.r-b.r)[0];if(hit)choose(hit.d)});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.72,Math.min(1.55,zoom-e.deltaY*.0007))},{passive:false});
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>setPanel(b.dataset.open)));$$('.close').forEach(b=>b.addEventListener('click',closePanels));$('.segmented').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;$$('.segmented button').forEach(x=>x.classList.toggle('active',x===b));renderConfig()});$('#baseUrl').addEventListener('input',renderConfig);$('#checkRuntime').addEventListener('click',checkRuntime);$('#copyConfig').addEventListener('click',async()=>{await navigator.clipboard.writeText($('#configOutput').textContent);$('#copyConfig').textContent='Copied';setTimeout(()=>$('#copyConfig').textContent='Copy mcp.json block',1300)});$('#heroUpload').addEventListener('change',uploadHero);$('#clearHero').addEventListener('click',clearHero);$('#focusButton').addEventListener('click',()=>{focus=!focus;document.body.classList.toggle('focus-mode',focus);$('#focusButton').textContent=focus?'Restore UI':'City focus';closePanels()});addEventListener('keydown',e=>{if(e.key==='Escape')closePanels()});addEventListener('resize',resize);
(async function init(){resize();buildDirectory();renderConfig();try{const saved=await dbGet();if(saved?.blob)applyVideo(saved.blob,saved.meta)}catch{$('#mediaReadout').textContent='Browser storage unavailable.'}requestAnimationFrame(frame)})();
