const DB='agentropolis-media',STORE='hero-assets',KEY='hero-video',MAX=200*1024*1024;
const districts=[
{id:'grid',name:'GRID CORE',role:'Runtime, memory, dispatch, and registry substrate.',x:-7,z:-3,w:3,h:8,d:3,color:'#00ffd0',status:'online'},
{id:'hermes',name:'HERMES DOCK',role:'Operator docking terminal for remote MCP configuration.',x:0,z:4,w:5,h:1.4,d:4,color:'#00b7ff',status:'ready'},
{id:'registry',name:'CAPABILITY REGISTRY',role:'Contract catalog for tools, Skills, and authority ceilings.',x:7,z:-3,w:3.5,h:8,d:3.5,color:'#9d4edd',status:'online'},
{id:'relay',name:'MCP RELAY',role:'Streamable HTTP gateway into the governed capability membrane.',x:-4.5,z:-9,w:3,h:6,d:3,color:'#39ff14',status:'remote'},
{id:'vault',name:'RECEIPT VAULT',role:'Evidence store for execution, authority, and audit receipts.',x:4.5,z:-9,w:4,h:5.5,d:4,color:'#f0cc6a',status:'sealed'},
{id:'risk',name:'RISK GATE',role:'Anti-Moloch slowdown and request risk classification.',x:0,z:-13,w:6.5,h:4.5,d:2.5,color:'#ff4064',status:'active'}
];
const canvas=document.querySelector('#cityCanvas'),ctx=canvas.getContext('2d'),video=document.querySelector('#heroVideo');
const selectedName=document.querySelector('#selectedName'),selectedRole=document.querySelector('#selectedRole'),selectedStatus=document.querySelector('#selectedStatus');
const directory=document.querySelector('#directory'),baseUrl=document.querySelector('#baseUrl'),runtimeReadout=document.querySelector('#runtimeReadout'),configOutput=document.querySelector('#configOutput');
const mediaReadout=document.querySelector('#mediaReadout'),mediaMeta=document.querySelector('#mediaMeta'),clearHero=document.querySelector('#clearHero');
let selected=districts[1],mode='native',yaw=-0.15,pitch=0.22,zoom=1,drag=false,lastX=0,lastY=0,objectUrl='';
function dbOpen(){return new Promise((r,j)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}
async function dbGet(){const d=await dbOpen();return new Promise((r,j)=>{const q=d.transaction(STORE).objectStore(STORE).get(KEY);q.onsuccess=()=>r(q.result||null);q.onerror=()=>j(q.error)})}
async function dbPut(file){const d=await dbOpen();return new Promise((r,j)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put({blob:file,meta:{name:file.name,type:file.type,size:file.size}},KEY);t.oncomplete=r;t.onerror=()=>j(t.error)})}
async function dbDelete(){const d=await dbOpen();return new Promise((r,j)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).delete(KEY);t.oncomplete=r;t.onerror=()=>j(t.error)})}
function normalize(v){try{const u=new URL(String(v||'').trim().replace(/\/+$/,''));if(u.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(u.hostname))return'';return u.toString().replace(/\/$/,'')}catch{return''}}
function resize(){const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
function project(x,y,z){const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);let rx=x*cy-z*sy,rz=x*sy+z*cy;let ry=y*cp-rz*sp;rz=y*sp+rz*cp+28;const f=760*zoom/Math.max(rz,3);return{x:innerWidth/2+rx*f,y:innerHeight*.62-ry*f,s:f,z:rz}}
function shade(hex,f){const n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)*f)),g=Math.max(0,Math.min(255,((n>>8)&255)*f)),b=Math.max(0,Math.min(255,(n&255)*f));return`rgb(${r|0},${g|0},${b|0})`}
function poly(points,fill,stroke,alpha=1){ctx.globalAlpha=alpha;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}ctx.globalAlpha=1}
function box(d,t){const y0=.15,y1=d.h+Math.sin(t*.001+d.x)*.05;const x0=d.x-d.w/2,x1=d.x+d.w/2,z0=d.z-d.d/2,z1=d.z+d.d/2;const p={a:project(x0,y0,z0),b:project(x1,y0,z0),c:project(x1,y0,z1),d:project(x0,y0,z1),A:project(x0,y1,z0),B:project(x1,y1,z0),C:project(x1,y1,z1),D:project(x0,y1,z1)};poly([p.a,p.b,p.B,p.A],shade(d.color,.22),d.color,.9);poly([p.b,p.c,p.C,p.B],shade(d.color,.15),d.color,.8);poly([p.d,p.a,p.A,p.D],shade(d.color,.1),d.color,.7);poly([p.A,p.B,p.C,p.D],shade(d.color,.4),d.color,1);if(selected.id===d.id){ctx.strokeStyle=d.color;ctx.lineWidth=3;ctx.strokeRect(p.A.x-7,p.A.y-7,14,14)}const label=project(d.x,y1+.9,d.z);ctx.font='700 11px ui-monospace,monospace';ctx.textAlign='center';ctx.fillStyle='#eefbf8';ctx.fillText(d.name,label.x,label.y);ctx.font='9px ui-monospace,monospace';ctx.fillStyle=d.color;ctx.fillText(d.status.toUpperCase(),label.x,label.y+14);d.hit={x:label.x,y:label.y+20,r:Math.max(28,d.w*14)};return p}
function drawGrid(){ctx.strokeStyle='rgba(0,255,208,.12)';ctx.lineWidth=1;for(let i=-22;i<=22;i+=2){let a=project(i,0,-22),b=project(i,0,12);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();a=project(-22,0,i);b=project(22,0,i);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}
function drawLinks(){const links=[['hermes','grid'],['hermes','registry'],['grid','relay'],['registry','vault'],['relay','risk'],['vault','risk']];ctx.setLineDash([5,6]);for(const [a,b] of links){const A=districts.find(x=>x.id===a),B=districts.find(x=>x.id===b),p=project(A.x,.25,A.z),q=project(B.x,.25,B.z);ctx.strokeStyle='rgba(0,183,255,.35)';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}ctx.setLineDash([])}
function render(t){ctx.clearRect(0,0,innerWidth,innerHeight);const g=ctx.createRadialGradient(innerWidth*.5,innerHeight*.45,10,innerWidth*.5,innerHeight*.55,innerWidth*.7);g.addColorStop(0,'rgba(0,183,255,.08)');g.addColorStop(1,'rgba(2,4,8,.78)');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight);drawGrid();drawLinks();[...districts].sort((a,b)=>b.z-a.z).forEach(d=>box(d,t));requestAnimationFrame(render)}
function selectDistrict(d){selected=d;selectedName.textContent=d.name;selectedRole.textContent=d.role;selectedStatus.textContent=d.status;document.querySelectorAll('.directory button').forEach(b=>b.classList.toggle('selected',b.dataset.id===d.id));if(d.id==='hermes')openPanel('hermes')}
function buildDirectory(){directory.innerHTML='';for(const d of districts){const b=document.createElement('button');b.dataset.id=d.id;b.innerHTML=`<i style="background:${d.color}"></i><span>${d.name}</span><small>${d.status}</small>`;b.onclick=()=>selectDistrict(d);directory.appendChild(b)}selectDistrict(selected)}
function openPanel(name){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('open'));document.querySelector(`#${name}Panel`).classList.add('open');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===name))}
function renderConfig(){const b=normalize(baseUrl.value)||'https://agentropolis-agent-mcp.YOUR-SUBDOMAIN.workers.dev',u=`${b}/mcp`;const server=mode==='native'?{url:u,transport:'streamable-http'}:{command:'npx',args:['-y','mcp-remote',u]};configOutput.textContent=JSON.stringify({mcpServers:{'agentropolis-grid':server}},null,2)}
async function checkRuntime(){const b=normalize(baseUrl.value);if(!b){runtimeReadout.className='readout offline';runtimeReadout.textContent='Enter a valid HTTPS Worker URL.';return}runtimeReadout.className='readout checking';runtimeReadout.textContent='Checking runtime...';try{const[h,m]=await Promise.all([fetch(`${b}/health`),fetch(`${b}/.well-known/mcp.json`)]);if(!h.ok||!m.ok)throw Error(`health=${h.status}, manifest=${m.status}`);const j=await h.json(),k=await m.json();runtimeReadout.className='readout online';runtimeReadout.textContent=`ONLINE · ${j.service||'agentropolis-agent-mcp'} · tools=${k?.tools?.length??'unknown'}`;document.querySelector('#topStatus').textContent='ONLINE · HERMES MCP'}catch(e){runtimeReadout.className='readout offline';runtimeReadout.textContent=`UNREACHABLE · ${e.message}`;document.querySelector('#topStatus').textContent='OFFLINE · HERMES MCP'}}
function setVideo(blob,meta){if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(blob);video.src=objectUrl;video.hidden=false;video.play().catch(()=>{});mediaReadout.textContent=`LOCAL HERO ACTIVE · ${meta.name}`;mediaMeta.hidden=false;mediaMeta.innerHTML=`<span>${meta.name}</span><small>${Math.round((meta.size||0)/1024/1024)} MB · stored in this browser</small>`;clearHero.disabled=false}
async function uploadHero(file){if(!['video/mp4','video/webm','video/ogg'].includes(file.type)){mediaReadout.textContent='BLOCKED · Use MP4, WebM, or Ogg.';return}if(file.size>MAX){mediaReadout.textContent='BLOCKED · Video exceeds 200 MB.';return}await dbPut(file);setVideo(file,{name:file.name,size:file.size})}
async function clearVideo(){await dbDelete();if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl='';video.pause();video.removeAttribute('src');video.load();video.hidden=true;mediaReadout.textContent='Hero video cleared.';mediaMeta.hidden=true;clearHero.disabled=true}
window.addEventListener('resize',resize);canvas.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-lastX)*.005;pitch=Math.max(-.05,Math.min(.55,pitch+(e.clientY-lastY)*.003));lastX=e.clientX;lastY=e.clientY});canvas.addEventListener('pointerup',e=>{drag=false;canvas.releasePointerCapture(e.pointerId)});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.65,Math.min(1.45,zoom-e.deltaY*.0008))},{passive:false});canvas.addEventListener('click',e=>{for(const d of districts){const h=d.hit;if(h&&Math.hypot(e.clientX-h.x,e.clientY-h.y)<h.r){selectDistrict(d);break}}});
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));document.querySelectorAll('.modes button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.modes button').forEach(x=>x.classList.toggle('active',x===b));renderConfig()});baseUrl.addEventListener('input',renderConfig);document.querySelector('#checkRuntime').onclick=checkRuntime;document.querySelector('#copyConfig').onclick=()=>navigator.clipboard.writeText(configOutput.textContent);document.querySelector('#heroUpload').onchange=e=>{const f=e.target.files?.[0];e.target.value='';if(f)uploadHero(f)};clearHero.onclick=clearVideo;
resize();buildDirectory();renderConfig();requestAnimationFrame(render);dbGet().then(a=>{if(a?.blob)setVideo(a.blob,a.meta||{name:'stored-video',size:a.blob.size})}).catch(()=>{mediaReadout.textContent='Browser storage unavailable.'});
